/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/nurse-audio.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

// Mapping of visemes to morph targets with intensity
// Using only the morph targets that exist in the model
const visemeToTargets = {
  // Closed mouth (M, B, P)
  A: [
    { name: "mouthClose", intensity: 0.7 },
    { name: "mouthPucker", intensity: 0.4 },
    { name: "mouthShrugUpper", intensity: 0.2 }
  ],
  
  // Wide (E, I)
  B: [
    { name: "mouthSmileLeft", intensity: 0.6 },
    { name: "mouthSmileRight", intensity: 0.6 },
    { name: "mouthStretchLeft", intensity: 0.3 },
    { name: "mouthStretchRight", intensity: 0.3 }
  ],
  
  // Wide open (A, I)
  C: [
    { name: "jawOpen", intensity: 0.8 },
    { name: "mouthUpperUp", intensity: 0.5 },
    { name: "mouthStretchLeft", intensity: 0.3 },
    { name: "mouthStretchRight", intensity: 0.3 }
  ],
  
  // Puckered (O, U)
  D: [
    { name: "mouthPucker", intensity: 0.9 },
    { name: "mouthFunnel", intensity: 0.6 },
    { name: "mouthShrugUpper", intensity: 0.4 }
  ],
  
  // F, V
  E: [
    { name: "mouthRollLower", intensity: 0.8 },
    { name: "mouthShrugLower", intensity: 0.6 },
    { name: "mouthLowerDownLeft", intensity: 0.4 },
    { name: "mouthLowerDownRight", intensity: 0.4 }
  ],
  
  // L, TH
  F: [
    { name: "tongueOut", intensity: 0.6 },
    { name: "tongueUp", intensity: 0.5 },
    { name: "mouthDimpleLeft", intensity: 0.4 },
    { name: "mouthDimpleRight", intensity: 0.4 }
  ],
  
  // Rest/Neutral - very subtle
  X: [
    { name: "neutral", intensity: 0.1 },
    { name: "mouthSmileLeft", intensity: 0.1 },
    { name: "mouthSmileRight", intensity: 0.1 }
  ]
};

// Map Rhubarb viseme values to our viseme groups
const mapRhubarbViseme = (rhubarbViseme) => {
  // Rhubarb viseme mapping to our viseme groups (A-F, X)
  const visemeMap = {
    // Closed mouth (M, B, P)
    'B': 'A', 'P': 'A', 'M': 'A', 'MBP': 'A',
    
    // Wide (E, I)
    'E': 'B', 'I': 'B', 'EAP': 'B', 'etc': 'B',
    
    // Wide open (A, I)
    'A': 'C', 'AI': 'C', 'O': 'C', 'AA': 'C', 'O': 'C',
    
    // Puckered (O, U)
    'U': 'D', 'WQ': 'D', 'O': 'D', 'U': 'D',
    
    // F, V
    'F': 'E', 'V': 'E', 'FV': 'E', 'TH': 'E',
    
    // L, TH, S, T, D
    'L': 'F', 'T': 'F', 'D': 'F', 'LTD': 'F', 'S': 'F', 'Z': 'F',
    
    // Default to neutral
    'rest': 'X',
    'idle': 'X',
    'X': 'X',
    'H': 'X',
    'R': 'X',
    'K': 'X',
    'N': 'X',
    'NG': 'X',
    'SH': 'X',
    'CH': 'X',
    'JH': 'X',
    'Y': 'X',
    'AW': 'X',
    'AY': 'X',
    'ER': 'X',
    'EY': 'X',
    'OY': 'X',
    'UH': 'X',
    'OW': 'X',
    'ZH': 'X',
    'sil': 'X',
    'pau': 'X'
  };
  
  // Normalize the viseme (remove any numbers or special characters)
  const normalizedViseme = rhubarbViseme.replace(/[0-9]/g, '');
  return visemeMap[normalizedViseme] || 'X';
};

// Simple mapping of viseme codes to friendly names for debugging
const visemeNames = {
  A: 'Closed (M, B, P)',
  B: 'Wide (E, I)',
  C: 'Open (A, I)',
  D: 'Puckered (O, U)',
  E: 'Fricative (F, V, S)',
  F: 'L/TH',
  X: 'Neutral'
};

// Map common phonemes to viseme groups
const phonemeToViseme = {
  // Closed
  'M': 'A', 'B': 'A', 'P': 'A',
  
  // Wide
  'E': 'B', 'I': 'B', 'Y': 'B',
  
  // Open
  'A': 'C', 'AA': 'C',
  
  // Rounded
  'O': 'D', 'W': 'D',
  
  // Fricatives
  'F': 'E', 'V': 'E', 'S': 'E', 'Z': 'E', 'SH': 'E', 'ZH': 'E',
  
  // Other
  'L': 'F', 'TH': 'F', 'D': 'F', 'T': 'F', 'N': 'F',
  
  // Default
  'rest': 'X'
};

// This will be populated with the first available target for each viseme
const corresponding = {};

// Helper function to find first available target
const findFirstAvailableTarget = (targets, mesh) => {
  if (!mesh) return targets[0]?.name || '';
  for (const target of targets) {
    const targetName = typeof target === 'string' ? target : target.name;
    if (mesh.morphTargetDictionary && mesh.morphTargetDictionary[targetName] !== undefined) {
      return target;
    }
  }
  return targets[0]; // Fallback to first target if none found
};

// Initialize corresponding object with the first available target for each viseme
const initCorresponding = (mesh) => {
  Object.entries(visemeToTargets).forEach(([viseme, targets]) => {
    corresponding[viseme] = findFirstAvailableTarget(targets, mesh);
  });
  console.log('Initialized viseme mappings:', corresponding);
};

let setupMode = false;

export function Avatar(props) {
  const { nodes, materials, scene } = useGLTF(
    "/models/nurse-audio.glb"
  );

  // Initialize viseme mappings and log available morph targets
  useEffect(() => {
    if (nodes) {
      // Log all nodes for debugging
      console.log('Available nodes:', Object.keys(nodes));
      
      // Find all meshes with morph targets
      const meshesWithMorphs = [];
      scene.traverse((child) => {
        if (child.isSkinnedMesh && child.morphTargetDictionary) {
          meshesWithMorphs.push({
            name: child.name,
            morphTargets: Object.keys(child.morphTargetDictionary)
          });
        }
      });
      
      console.log('Meshes with morph targets:', meshesWithMorphs);
      
      // Find the main head or face mesh that contains morph targets
      const headMesh = Object.values(nodes).find(
        node => node.isMesh && 
               node.morphTargetDictionary && 
               Object.keys(node.morphTargetDictionary).length > 0
      );
      
      if (headMesh) {
        console.log('Using mesh for visemes:', headMesh.name);
        console.log('Available morph targets:', Object.keys(headMesh.morphTargetDictionary));
        
        // Initialize viseme mappings with the first available mesh that has morph targets
        initCorresponding(headMesh);
      } else if (meshesWithMorphs.length > 0) {
        // If we found meshes with morph targets but no head mesh, use the first one
        console.warn('No head mesh found, using first mesh with morph targets:', meshesWithMorphs[0].name);
        initCorresponding(scene.getObjectByName(meshesWithMorphs[0].name));
      } else {
        console.warn('No mesh with morph targets found in the model');
        // Initialize with default mappings as fallback
        initCorresponding();
      }
    }
  }, [nodes]);

  const { message, onMessagePlayed, chat } = useChat();

  const [lipsync, setLipsync] = useState();

  useEffect(() => {
    console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }
    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    setLipsync(message.lipsync);
    const audio = new Audio("data:audio/mp3;base64," + message.audio);
    audio.play();
    setAudio(audio);
    audio.onended = onMessagePlayed;
  }, [message]);

  const { animations } = useGLTF("/models/animations.glb");

  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : animations[0].name // Check if Idle animation exists otherwise use first animation
  );
  // Disable all animations except Idle and Talking
  useEffect(() => {
    try {
      // Stop all actions first
      Object.values(actions).forEach(action => {
        if (action) {
          action.stop();
          action.fadeOut(0.3);
        }
      });

      // Only allow Idle and Talking animations
      const allowedAnimations = ['Idle', 'Talking', 'Talk'];
      const actionToPlay = allowedAnimations.includes(animation) ? actions[animation] : actions['Idle'];
      
      if (actionToPlay) {
        actionToPlay.reset().fadeIn(0.3).play();
      }
      
      return () => {
        if (actionToPlay?.fadeOut) {
          actionToPlay.fadeOut(0.3);
        }
      };
    } catch (error) {
      console.error('Error playing animation:', error);
      return () => {}; // Return empty cleanup function
    }
  }, [animation]);

  // Simple animation states for lip sync
const lipSyncStates = {
  currentState: 'neutral',
  intensity: 0,
  targetIntensity: 0,
  speed: 0.1
};

const lerpMorphTarget = (target, value, speed = 0.1) => {
  if (!scene) return;
  
  // Target the main head mesh and teeth for mouth movements
  const targetMeshes = ['Wolf3D_Head', 'Wolf3D_Teeth'];
  let targetFound = false;
  
  scene.traverse((child) => {
    if (child.isSkinnedMesh && child.morphTargetDictionary && targetMeshes.includes(child.name)) {
      const index = child.morphTargetDictionary[target];
      
      if (index !== undefined) {
        // Initialize morphTargetInfluences if needed
        if (!child.morphTargetInfluences || child.morphTargetInfluences.length === 0) {
          child.morphTargetInfluences = new Array(Object.keys(child.morphTargetDictionary).length).fill(0);
        }
        
        // Apply the morph target with smoothing
        if (child.morphTargetInfluences[index] === undefined) {
          child.morphTargetInfluences[index] = 0;
        }
        
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );
        
        targetFound = true;
      }
    }
  });
  
  // Debug log for missing targets
  if (process.env.NODE_ENV === 'development' && !targetFound) {
    console.warn(`Morph target '${target}' not found in any relevant mesh`);
  }
};

const [blink, setBlink] = useState(false);
const [winkLeft, setWinkLeft] = useState(false);
const [winkRight, setWinkRight] = useState(false);
const [facialExpression, setFacialExpression] = useState("");
const [audio, setAudio] = useState();

  // Log available morph targets once
  useEffect(() => {
    console.log('Available meshes with morph targets:');
    Object.entries(nodes).forEach(([name, node]) => {
      if (node.isMesh && node.morphTargetDictionary) {
        console.log(`Mesh: ${name}`, Object.keys(node.morphTargetDictionary));
      }
    });
  }, []);

  useFrame(() => {
    // Handle eye blinks
    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);

    // Apply facial expressions if any
    if (!setupMode && nodes.Wolf3D_Head?.morphTargetDictionary) {
      Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        }
      });
    }

    // LIPSYNC with morph targets
    if (setupMode || !message || !lipsync || !audio) return;
    
    const currentAudioTime = audio.currentTime;
    let currentViseme = 'X'; // Default to rest position
    
    // Debug: Log all available morph targets on first run
    if (!window.morphTargetsLogged) {
      console.log('Available meshes with morph targets:');
      Object.entries(nodes).forEach(([name, node]) => {
        if (node.isMesh && node.morphTargetDictionary) {
          console.log(`Mesh: ${name}`, Object.keys(node.morphTargetDictionary));
        }
      });
      window.morphTargetsLogged = true;
    }
    
    // Find the current viseme based on audio time
    if (lipsync.mouthCues) {
      // Find all active mouth cues (in case of overlapping)
      const activeCues = lipsync.mouthCues.filter(
        cue => currentAudioTime >= cue.start && currentAudioTime <= cue.end
      );
      
      if (activeCues.length > 0) {
        // Use the most significant (longest) active cue
        const mainCue = activeCues.reduce((longest, cue) => 
          (cue.end - cue.start > longest.end - longest.start) ? cue : longest
        );
        
        // Map Rhubarb viseme values to our viseme groups
        currentViseme = mapRhubarbViseme(mainCue.value);
        
        // Debug log current viseme
        if (process.env.NODE_ENV === 'development' && currentViseme !== 'X') {
          console.log('Current viseme:', currentViseme, 'from', mainCue.value);
        }
      }
    }
    
    // Get the targets for the current viseme
    const targets = visemeToTargets[currentViseme] || [];
    
    // Debug log current viseme and targets (throttled to avoid console spam)
    if (process.env.NODE_ENV === 'development') {
      const now = Date.now();
      if (!window.lastVisemeLog || now - window.lastVisemeLog > 500) {
        console.log(`Viseme: ${currentViseme} (${visemeNames[currentViseme] || 'Unknown'})`);
        console.log('Targets:', targets);
        window.lastVisemeLog = now;
      }
    }
    
    // Track which morph targets we've set in this frame
    const activeMorphTargets = new Set();
    
    // Apply current viseme targets with smooth transitions
    targets.forEach(({ name, intensity }) => {
      if (name) {
        activeMorphTargets.add(name);
        lerpMorphTarget(name, intensity, 0.15);
      }
    });
    
    // Reset only the morph targets that aren't part of the current viseme
    if (nodes.Wolf3D_Head?.morphTargetDictionary) {
      Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).forEach(key => {
        if (!activeMorphTargets.has(key) && 
            key !== 'eyeBlinkLeft' && 
            key !== 'eyeBlinkRight' &&
            key !== 'neutral') {
          lerpMorphTarget(key, 0, 0.1);
        }
      });
    }
    
    // Apply viseme targets to all relevant meshes
    const targetMeshes = ['Wolf3D_Head', 'Wolf3D_Teeth'];
    let foundTarget = false;
    
    // Debug log current viseme
    if (process.env.NODE_ENV === 'development' && currentViseme !== 'X') {
      console.log('Current viseme:', currentViseme, mainCue ? `from ${mainCue.value}` : '');
    }
    
    if (!foundTarget && process.env.NODE_ENV === 'development') {
      console.warn(`No valid morph targets found for viseme ${currentViseme}`);
    }
  });

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key) => {
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight") {
          return; // eyes wink/blink are handled separately
        }
        const value =
          nodes.EyeLeft.morphTargetInfluences[
            nodes.EyeLeft.morphTargetDictionary[key]
          ];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(nodes.EyeLeft.morphTargetDictionary).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: nodes.EyeLeft.morphTargetInfluences[
              nodes.EyeLeft.morphTargetDictionary[key]
            ],
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh
        name="Wolf3D_Body"
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Bottom"
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Footwear"
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Outfit_Top"
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />
      <skinnedMesh
        name="Wolf3D_Hair"
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />
      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("/models/nurse-audio.glb");
useGLTF.preload("/models/animations.glb");
