
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import {
  Lightbulb,
  Loader2,
  BookHeart,
  BookOpen,
  Volume2,
  Sparkles,
  HelpCircle,
  GraduationCap,
} from 'lucide-react';
import { generateStoryAction } from '@/app/actions';
import type { StorytellingOutput } from '@/ai/schemas/storytelling';
import PageHeader from '@/components/page-header';
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription,
} from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { useToast } from '@/hooks/use-toast';
import { Separator } from '@/components/ui/separator';
import { Label } from '@/components/ui/label';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';


const languages = [
  { value: 'hindi', label: 'Hindi' },
  { value: 'english', label: 'English' },
  { value: 'bengali', label: 'Bengali' },
  { value: 'tamil', label: 'Tamil' },
  { value: 'telugu', label: 'Telugu' },
  { value: 'marathi', label: 'Marathi' },
];

const formSchema = z.object({
  language: z.string().min(1, 'Please select a language.'),
  proficiency: z.enum(['beginner', 'intermediate', 'advanced'], {
    required_error: 'Please select your proficiency level.',
  }),
});

export default function StoryTimePage() {
  const [storyLesson, setStoryLesson] = useState<StorytellingOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedAnswer, setSelectedAnswer] = useState<string | null>(null);
  const [isQuestionAnswered, setIsQuestionAnswered] = useState(false);
  const { toast } = useToast();

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      language: 'hindi',
      proficiency: 'beginner',
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsLoading(true);
    setStoryLesson(null);
    setSelectedAnswer(null);
    setIsQuestionAnswered(false);
    try {
      const result = await generateStoryAction(values);
      setStoryLesson(result);
    } catch (error) {
      console.error(error);
      toast({
        variant: 'destructive',
        title: 'An error occurred',
        description: 'Failed to generate a story. Please try again.',
      });
    } finally {
      setIsLoading(false);
    }
  }

  const handlePlayNarration = () => {
    if (storyLesson?.audioNarrationUri) {
      const audio = new Audio(storyLesson.audioNarrationUri);
      audio.play();
    }
  };
  
  const checkAnswer = () => {
    if (!storyLesson || !selectedAnswer) return;
    setIsQuestionAnswered(true);
    if (selectedAnswer === storyLesson.comprehensionQuestion.answer) {
        toast({
            title: 'Correct!',
            description: 'Great job understanding the story.',
        });
    } else {
        toast({
            variant: 'destructive',
            title: 'Not quite!',
            description: `The correct answer was: "${storyLesson.comprehensionQuestion.answer}"`,
        });
    }
  }

  return (
    <div className="flex flex-col gap-8">
      <PageHeader
        title="Cultural Story Time"
        description="Learn language and culture through engaging folktales generated by AI."
      />
      <div className="grid grid-cols-1 gap-8 lg:grid-cols-3">
        <div className="lg:col-span-1">
          <Card>
            <CardHeader>
              <CardTitle>Create Your Story</CardTitle>
              <CardDescription>
                Select a language and your level to begin.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Form {...form}>
                <form
                  onSubmit={form.handleSubmit(onSubmit)}
                  className="space-y-6"
                >
                  <FormField
                    control={form.control}
                    name="language"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Language</FormLabel>
                        <Select
                          onValueChange={field.onChange}
                          defaultValue={field.value}
                        >
                          <FormControl>
                            <SelectTrigger>
                              <SelectValue placeholder="Select a language" />
                            </SelectTrigger>
                          </FormControl>
                          <SelectContent>
                            {languages.map((lang) => (
                              <SelectItem key={lang.value} value={lang.value}>
                                {lang.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="proficiency"
                    render={({ field }) => (
                      <FormItem className="space-y-3">
                        <FormLabel>Proficiency Level</FormLabel>
                        <FormControl>
                          <RadioGroup
                            onValueChange={field.onChange}
                            defaultValue={field.value}
                            className="flex gap-4"
                          >
                            <FormItem className="flex items-center space-x-2 space-y-0">
                              <FormControl>
                                <RadioGroupItem value="beginner" />
                              </FormControl>
                              <FormLabel className="font-normal capitalize">
                                Beginner
                              </FormLabel>
                            </FormItem>
                            <FormItem className="flex items-center space-x-2 space-y-0">
                              <FormControl>
                                <RadioGroupItem value="intermediate" />
                              </FormControl>
                              <FormLabel className="font-normal capitalize">
                                Intermediate
                              </FormLabel>
                            </FormItem>
                            <FormItem className="flex items-center space-x-2 space-y-0">
                              <FormControl>
                                <RadioGroupItem value="advanced" />
                              </FormControl>
                              <FormLabel className="font-normal capitalize">
                                Advanced
                              </FormLabel>
                            </FormItem>
                          </RadioGroup>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <Button type="submit" disabled={isLoading} className="w-full">
                    {isLoading ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Sparkles className="mr-2 h-4 w-4" />
                    )}
                    Generate Story
                  </Button>
                </form>
              </Form>
            </CardContent>
          </Card>
        </div>
        <div className="lg:col-span-2">
            <Card className="min-h-full">
              <CardHeader>
                <CardTitle className="flex items-center justify-between text-2xl">
                    <div className="flex items-center gap-2">
                        <BookHeart className="text-primary"/>
                        {storyLesson?.title || 'Your Story'}
                    </div>
                     <Button
                        variant="outline"
                        size="sm"
                        onClick={handlePlayNarration}
                        disabled={!storyLesson?.audioNarrationUri || isLoading}
                     >
                        <Volume2 className="mr-2"/>
                        Listen
                    </Button>
                </CardTitle>
                <CardDescription>
                  Read the story, learn new words, and test your understanding.
                </CardDescription>
              </CardHeader>
              <CardContent>
                {isLoading && (
                    <div className="flex h-full min-h-[400px] items-center justify-center">
                        <div className="flex flex-col items-center gap-4 text-muted-foreground">
                            <Loader2 className="h-12 w-12 animate-spin text-primary" />
                            <p className="text-lg">Crafting a tale for you...</p>
                        </div>
                    </div>
                )}
                 {storyLesson ? (
                     <div className="space-y-6">
                        {/* Story Text */}
                        <div>
                             <h3 className="mb-2 flex items-center gap-2 font-headline text-lg font-semibold"><BookOpen/> The Story</h3>
                             <p className="prose prose-sm max-w-none whitespace-pre-wrap rounded-md bg-muted/50 p-4">{storyLesson.story}</p>
                        </div>
                        <Separator/>
                        {/* Vocabulary */}
                        <div>
                             <h3 className="mb-2 flex items-center gap-2 font-headline text-lg font-semibold"><GraduationCap/> Vocabulary</h3>
                             <TooltipProvider>
                                <div className="flex flex-wrap gap-2">
                                    {storyLesson.vocabulary.map(v => (
                                        <Tooltip key={v.wordInStory}>
                                            <TooltipTrigger asChild>
                                                <span className="cursor-pointer rounded-full border-2 border-dashed border-accent bg-accent/20 px-3 py-1 text-sm font-medium text-accent-foreground">{v.wordInStory}</span>
                                            </TooltipTrigger>
                                            <TooltipContent>
                                                <p className="font-bold">{v.baseForm}: <span className="font-normal">{v.definition}</span></p>
                                            </TooltipContent>
                                        </Tooltip>
                                    ))}
                                </div>
                            </TooltipProvider>
                        </div>
                         <Separator/>
                        {/* Comprehension Question */}
                        <div>
                            <h3 className="mb-2 flex items-center gap-2 font-headline text-lg font-semibold"><HelpCircle/> Comprehension Check</h3>
                            <div className="space-y-3 rounded-lg border p-4">
                                <p className="font-medium">{storyLesson.comprehensionQuestion.question}</p>
                                 <RadioGroup onValueChange={setSelectedAnswer} disabled={isQuestionAnswered}>
                                    {storyLesson.comprehensionQuestion.options.map((option, i) => (
                                    <div key={i} className="flex items-center space-x-2">
                                        <RadioGroupItem value={option} id={`q-opt-${i}`} />
                                        <Label htmlFor={`q-opt-${i}`}>{option}</Label>
                                    </div>
                                    ))}
                                </RadioGroup>
                                <Button onClick={checkAnswer} disabled={!selectedAnswer || isQuestionAnswered}>Check Answer</Button>
                            </div>
                        </div>
                         <Separator/>
                         {/* Cultural Note */}
                        <div>
                             <h3 className="mb-2 flex items-center gap-2 font-headline text-lg font-semibold"><Lightbulb/> Cultural Note</h3>
                             <p className="text-sm text-muted-foreground italic">{storyLesson.culturalNote}</p>
                        </div>
                     </div>
                 ) : (
                    !isLoading && (
                        <div className="flex h-full min-h-[400px] items-center justify-center">
                            <div className="text-center text-muted-foreground">
                                <BookHeart className="mx-auto mb-4 h-16 w-16" />
                                <p className="text-lg">Your generated story will appear here.</p>
                            </div>
                        </div>
                    )
                 )}
              </CardContent>
            </Card>
        </div>
      </div>
    </div>
  );
}
