import type { LanguageData } from "@/types";

// Note: The stroke data is simplified for demonstration purposes.
// A real application would require more precise vector data for each character.
export const ALPHABET_DATA: { [key: string]: LanguageData } = {
  english: {
    name: "English",
    iconId: "english-lang-icon",
    alphabets: [
      { char: "A" },
      { char: "B" },
      { char: "C" },
      { char: "D" },
      { char: "E" },
      { char: "F" },
      { char: "G" },
      { char: "H" },
      { char: "I" },
      { char: "J" },
      { char: "K" },
      { char: "L" },
      { char: "M" },
      { char: "N" },
      { char: "O" },
      { char: "P" },
      { char: "Q" },
      { char: "R" },
      { char: "S" },
      { char: "T" },
      { char: "U" },
      { char: "V" },
      { char: "W" },
      { char: "X" },
      { char: "Y" },
      { char: "Z" },
    ],
  },
  malayalam: {
    name: "Malayalam",
    iconId: "malayalam-lang-icon",
    alphabets: [
      { char: "അ" },
      { char: "ആ" },
      { char: "ഇ" },
      { char: "ഈ" },
      { char: "ഉ" },
      { char: "ഊ" },
      { char: "ഋ" },
      { char: "എ" },
      { char: "ഏ" },
      { char: "ഐ" },
      { char: "ഒ" },
      { char: "ഓ" },
      { char: "ഔ" },
      { char: "ക" },
      { char: "ഖ" },
      { char: "ഗ" },
      { char: "ഘ" },
      { char: "ങ" },
      { char: "ച" },
      { char: "ഛ" },
      { char: "ജ" },
      { char: "ഝ" },
      { char: "ഞ" },
      { char: "ട" },
      { char: "ഠ" },
      { char: "ഡ" },
      { char: "ഢ" },
      { char: "ണ" },
      { char: "ത" },
      { char: "ഥ" },
      { char: "ദ" },
      { char: "ധ" },
      { char: "ന" },
      { char: "പ" },
      { char: "ഫ" },
      { char: "ബ" },
      { char: "ഭ" },
      { char: "മ" },
      { char: "യ" },
      { char: "ര" },
      { char: "ല" },
      { char: "വ" },
      { char: "ശ" },
      { char: "ഷ" },
      { char: "സ" },
      { char: "ഹ" },
      { char: "ള" },
      { char: "ഴ" },
      { char: "റ" },
    ],
  },
  hindi: {
    name: "Hindi",
    iconId: "hindi-lang-icon",
    alphabets: [
      { char: "अ" },
      { char: "आ" },
      { char: "इ" },
      { char: "ई" },
      { char: "उ" },
      { char: "ऊ" },
      { char: "ऋ" },
      { char: "ए" },
      { char: "ऐ" },
      { char: "ओ" },
      { char: "औ" },
      { char: "क" },
      { char: "ख" },
      { char: "ग" },
      { char: "घ" },
      { char: "ङ" },
      { char: "च" },
      { char: "छ" },
      { char: "ज" },
      { char: "झ" },
      { char: "ञ" },
      { char: "ट" },
      { char: "ठ" },
      { char: "ड" },
      { char: "ढ" },
      { char: "ण" },
      { char: "त" },
      { char: "थ" },
      { char: "द" },
      { char: "ध" },
      { char: "न" },
      { char: "प" },
      { char: "फ" },
      { char: "ब" },
      { char: "भ" },
      { char: "म" },
      { char: "य" },
      { char: "र" },
      { char: "ल" },
      { char: "व" },
      { char: "श" },
      { char: "ष" },
      { char: "स" },
      { char: "ह" },
      { char: "ज्ञ" },
      { char: "क्ष" },
      { char: "श्र" },
      { char: "त्र" },
    ],
  },
  kannada: {
    name: "Kannada",
    iconId: "kannada-lang-icon",
    alphabets: [
      { char: "ಅ" },
      { char: "ಆ" },
      { char: "ಇ" },
      { char: "ಈ" },
      { char: "ಉ" },
      { char: "ಊ" },
      { char: "ಋ" },
      { char: "ಎ" },
      { char: "ಏ" },
      { char: "ಐ" },
      { char: "ಒ" },
      { char: "ಓ" },
      { char: "ಔ" },
      { char: "ಕ" },
      { char: "ಖ" },
      { char: "ಗ" },
      { char: "ಘ" },
      { char: "ಙ" },
      { char: "ಚ" },
      { char: "ಛ" },
      { char: "ಜ" },
      { char: "ಝ" },
      { char: "ಞ" },
      { char: "ಟ" },
      { char: "ಠ" },
      { char: "ಡ" },
      { char: "ಢ" },
      { char: "ಣ" },
      { char: "ತ" },
      { char: "ಥ" },
      { char: "ದ" },
      { char: "ಧ" },
      { char: "ನ" },
      { char: "ಪ" },
      { char: "ಫ" },
      { char: "ಬ" },
      { char: "ಭ" },
      { char: "ಮ" },
      { char: "ಯ" },
      { char: "ರ" },
      { char: "ಲ" },
      { char: "ವ" },
      { char: "ಶ" },
      { char: "ಷ" },
      { char: "ಸ" },
      { char: "ಹ" },
      { char: "ಳ" },
    ]
  },
  tamil: {
    name: "Tamil",
    iconId: "tamil-lang-icon",
    alphabets: [
      { char: "அ" },
      { char: "ஆ" },
      { char: "இ" },
      { char: "ஈ" },
      { char: "உ" },
      { char: "ஊ" },
      { char: "எ" },
      { char: "ஏ" },
      { char: "ஐ" },
      { char: "ஒ" },
      { char: "ஓ" },
      { char: "ஔ" },
      { char: "க" },
      { char: "ங" },
      { char: "ச" },
      { char: "ஞ" },
      { char: "ட" },
      { char: "ண" },
      { char: "த" },
      { char: "ந" },
      { char: "ப" },
      { char: "ம" },
      { char: "ய" },
      { char: "ர" },
      { char: "ல" },
      { char: "வ" },
      { char: "ழ" },
      { char: "ள" },
      { char: "ற" },
      { char: "ன" },
    ]
  },
  telugu: {
    name: "Telugu",
    iconId: "telugu-lang-icon",
    alphabets: [
      { char: "అ" },
      { char: "ఆ" },
      { char: "ఇ" },
      { char: "ఈ" },
      { char: "ఉ" },
      { char: "ఊ" },
      { char: "ఋ" },
      { char: "ఎ" },
      { char: "ఏ" },
      { char: "ఐ" },
      { char: "ఒ" },
      { char: "ఓ" },
      { char: "ఔ" },
      { char: "క" },
      { char: "ఖ" },
      { char: "గ" },
      { char: "ఘ" },
      { char: "ఙ" },
      { char: "చ" },
      { char: "ఛ" },
      { char: "జ" },
      { char: "ఝ" },
      { char: "ఞ" },
      { char: "ట" },
      { char: "ఠ" },
      { char: "డ" },
      { char: "ఢ" },
      { char: "ణ" },
      { char: "త" },
      { char: "థ" },
      { char: "ద" },
      { char: "ధ" },
      { char: "న" },
      { char: "ప" },
      { char: "ఫ" },
      { char: "బ" },
      { char: "భ" },
      { char: "మ" },
      { char: "య" },
      { char: "ర" },
      { char: "ల" },
      { char: "వ" },
      { char: "శ" },
      { char: "ష" },
      { char: "స" },
      { char: "హ" },
      { char: "ళ" },
    ]
  }
};
